# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoodWall' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire'
    pod 'IQKeyboardManager'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'IQKeyboardManager'
    pod 'SwiftSVG', '~> 2.0'
  # Pods for GoodWall

  target 'GoodWallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoodWallUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
